server:
  port: 9002
spring:
  application:
    name: consumer-resttemplate
  profiles:
    active: native
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
