server:
  port: 9001
spring:
  application:
    name: compute-service
  profiles:
    active: native

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
