package com.bosssoft.hr.train.springboot.basic.example.pojo.entity;

import javax.persistence.*;

@Table(name = "t_department")
public class Department extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.mnemonic_code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String mnemonicCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.level
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.parent_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.master
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String master;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_department.descript
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String descript;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.name
     *
     * @return the value of t_department.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.name
     *
     * @param name the value for t_department.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.mnemonic_code
     *
     * @return the value of t_department.mnemonic_code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getMnemonicCode() {
        return mnemonicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.mnemonic_code
     *
     * @param mnemonicCode the value for t_department.mnemonic_code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setMnemonicCode(String mnemonicCode) {
        this.mnemonicCode = mnemonicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.code
     *
     * @return the value of t_department.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.code
     *
     * @param code the value for t_department.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.level
     *
     * @return the value of t_department.level
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.level
     *
     * @param level the value for t_department.level
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.parent_id
     *
     * @return the value of t_department.parent_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.parent_id
     *
     * @param parentId the value for t_department.parent_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.master
     *
     * @return the value of t_department.master
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.master
     *
     * @param master the value for t_department.master
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setMaster(String master) {
        this.master = master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_department.descript
     *
     * @return the value of t_department.descript
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getDescript() {
        return descript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_department.descript
     *
     * @param descript the value for t_department.descript
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setDescript(String descript) {
        this.descript = descript;
    }
}