package com.bosssoft.hr.train.springboot.basic.example.pojo.entity;

import javax.persistence.*;

@Table(name = "t_organization")
public class Organization extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.master
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String master;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.tel
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_organization.address
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.name
     *
     * @return the value of t_organization.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.name
     *
     * @param name the value for t_organization.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.code
     *
     * @return the value of t_organization.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.code
     *
     * @param code the value for t_organization.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.master
     *
     * @return the value of t_organization.master
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getMaster() {
        return master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.master
     *
     * @param master the value for t_organization.master
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setMaster(String master) {
        this.master = master;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.tel
     *
     * @return the value of t_organization.tel
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.tel
     *
     * @param tel the value for t_organization.tel
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_organization.address
     *
     * @return the value of t_organization.address
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_organization.address
     *
     * @param address the value for t_organization.address
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }
}