package com.bosssoft.hr.train.springboot.basic.example.pojo.entity;

import javax.persistence.*;

@Table(name = "t_resource")
public class Resource extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.parent_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.component
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String component;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.url
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.open_img
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String openImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.close_img
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String closeImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_type
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Byte resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.leaf
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Byte leaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.remark
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.order
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Long order;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.name
     *
     * @return the value of t_resource.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.name
     *
     * @param name the value for t_resource.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.code
     *
     * @return the value of t_resource.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.code
     *
     * @param code the value for t_resource.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.parent_id
     *
     * @return the value of t_resource.parent_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.parent_id
     *
     * @param parentId the value for t_resource.parent_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.component
     *
     * @return the value of t_resource.component
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.component
     *
     * @param component the value for t_resource.component
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setComponent(String component) {
        this.component = component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.url
     *
     * @return the value of t_resource.url
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.url
     *
     * @param url the value for t_resource.url
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.open_img
     *
     * @return the value of t_resource.open_img
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getOpenImg() {
        return openImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.open_img
     *
     * @param openImg the value for t_resource.open_img
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setOpenImg(String openImg) {
        this.openImg = openImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.close_img
     *
     * @return the value of t_resource.close_img
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getCloseImg() {
        return closeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.close_img
     *
     * @param closeImg the value for t_resource.close_img
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setCloseImg(String closeImg) {
        this.closeImg = closeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_type
     *
     * @return the value of t_resource.resource_type
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Byte getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_type
     *
     * @param resourceType the value for t_resource.resource_type
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setResourceType(Byte resourceType) {
        this.resourceType = resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.leaf
     *
     * @return the value of t_resource.leaf
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Byte getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.leaf
     *
     * @param leaf the value for t_resource.leaf
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setLeaf(Byte leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.remark
     *
     * @return the value of t_resource.remark
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.remark
     *
     * @param remark the value for t_resource.remark
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.order
     *
     * @return the value of t_resource.order
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Long getOrder() {
        return order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.order
     *
     * @param order the value for t_resource.order
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setOrder(Long order) {
        this.order = order;
    }
}