package com.bosssoft.hr.train.springboot.basic.example.pojo.entity;

import javax.persistence.*;

@Table(name = "t_role_resource")
public class RoleResource extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.resource_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Long resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_resource.role_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Long roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.resource_id
     *
     * @return the value of t_role_resource.resource_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Long getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.resource_id
     *
     * @param resourceId the value for t_role_resource.resource_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setResourceId(Long resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_resource.role_id
     *
     * @return the value of t_role_resource.role_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_resource.role_id
     *
     * @param roleId the value for t_role_resource.role_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }
}