package com.bosssoft.hr.train.springboot.basic.example.pojo.entity;

import java.util.Date;
import javax.persistence.*;

@Table(name = "t_user")
public class User extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Byte sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.position_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Long positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.tel
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.other
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String other;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.remark
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.department_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private Long departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.profile_picture
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String profilePicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.avatar
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.code
     *
     * @return the value of t_user.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.code
     *
     * @param code the value for t_user.code
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.name
     *
     * @return the value of t_user.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.name
     *
     * @param name the value for t_user.name
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthday
     *
     * @return the value of t_user.birthday
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthday
     *
     * @param birthday the value for t_user.birthday
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.position_id
     *
     * @return the value of t_user.position_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Long getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.position_id
     *
     * @param positionId the value for t_user.position_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setPositionId(Long positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.tel
     *
     * @return the value of t_user.tel
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.tel
     *
     * @param tel the value for t_user.tel
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.other
     *
     * @return the value of t_user.other
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getOther() {
        return other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.other
     *
     * @param other the value for t_user.other
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setOther(String other) {
        this.other = other;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.remark
     *
     * @return the value of t_user.remark
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.remark
     *
     * @param remark the value for t_user.remark
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.department_id
     *
     * @return the value of t_user.department_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public Long getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.department_id
     *
     * @param departmentId the value for t_user.department_id
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.profile_picture
     *
     * @return the value of t_user.profile_picture
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getProfilePicture() {
        return profilePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.profile_picture
     *
     * @param profilePicture the value for t_user.profile_picture
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.avatar
     *
     * @return the value of t_user.avatar
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.avatar
     *
     * @param avatar the value for t_user.avatar
     *
     * @mbg.generated Thu Jun 25 14:51:09 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}