server:
  port: 8181
spring:
  application:
    name: mybatisplus-demo
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bosssoft?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
