spring:
  datasource:
    url: jdbc:mysql://112.124.21.230:3306/bosssoft?useSSl=false&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181
