server:
  port: 8181
spring:
  application:
    name: tk.mybatis-demo
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bosssoft?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/*.xml
logging:
  level:
    com.bosssoft.hr.train.dao: debug
pagehelper:
  reasonable: true
