server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#  devtools:
#    restart:
#      enabled: true
#      additional-paths: src/main/java
management:
  endpoints:
    web:
      exposure:
        include: '*'
