spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_cache?useSSL=false&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.214.214
    port: 12346

mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.atguigu.cache.mapper: debug