spring:
  application:
    name: zuul-service
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    add:
      path: /add/**
      serviceId: compute-service
    test:
      path: /test/**
      url: http://localhost:9001/